implement exercise submission/commit
amplimindcc/frontend pull request #13
Opened 2024-04-10 07:44 UTC by ImpyKid

2024-04-10 13:53 UTC, cwsyth submitted a review, later dismissed
optionaler Chat mit Text Input? oder kommt das später?

2024-04-10 14:13 UTC, ImpyKid commented
Stimmt, danke für den Hinweis. Dann implementiere ich heute Abend noch ein kleines "Chatsystem".

2024-04-10 14:23 UTC, MysterionAutotronic commented
Muss ja nur eine Textarea sein

2024-04-10 18:34 UTC, MysterionAutotronic requested changes
TypeScript Fehler
![grafik](https://github.com/amplimindcc/frontend/assets/76444188/6ec47209-1686-4cf3-bb2c-2914b891e30d)

Property 'chatMessage' does not exist on type 'EventTarget'.ts(2339)

Check mal ob deine Datentypen passen

2024-04-10 18:54 UTC, ImpyKid commented
Tut mir echt leid, unerfahrener Reacter hier. Hoffe, es passt jetzt. <3

2024-04-10 20:01 UTC, MysterionAutotronic commented
Da sind leider tatsächlich noch einige Dinge:

- einige Indents passen nicht (formatier das Dokument am besten einmal mit prettier)
- der optionale Chat war nur als Feld für Anmerkungen gemeint, die einmalig beim submitten mitgegeben werden. Der Input mit dem send Message wird also nicht gebraucht
- var sollte in TypeScript nicht verwendet werden
- Du solltest die Werte aus dem Form auf React States mappen um sie später verwenden zu können. Wie das geht, kannst du z.B. in Users.tsx oder Login.tsx sehen

Wenn du noch Fragen hast kannst die gerne hier reinschreiben oder mir ne Discord PN schreiben, dann können wir das gerne in einem Call besprechen

2024-04-11 05:00 UTC, ImpyKid commented
> der optionale Chat war nur als Feld für Anmerkungen gemeint, die einmalig beim submitten mitgegeben werden. Der Input mit dem send Message wird also nicht gebraucht

Sorry, das hatte ich nicht mehr auf dem Schirm. Ist nun eine einfache Textarea, welche beim Submit mitgesendet wird.
> var sollte in TypeScript nicht verwendet werden

Ist durch das falsch verstandene Chatsystem, was ich nun entfernt habe, weggefallen. Dennoch danke für den Hinweis.
> Du solltest die Werte aus dem Form auf React States mappen um sie später verwenden zu können. Wie das geht, kannst du z.B. in Users.tsx oder Login.tsx sehen

Ist getan.

Ich hoffe echt, dass es nun passt. Und echt nochmal sorry. ^^'

2024-04-11 07:45 UTC, MysterionAutotronic approved these changes
Sieht jetzt alles gut aus

2024-04-11 07:46 UTC, merged